server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri:  file:///${user.home}/cloud-config
          searchPaths: '{application}/{profile}'
  